name: Sync Fork

on:
  schedule:
    - cron: '0 18 */3 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1
        with:
          owner: openmediavault
          base: master
          head: master
          pr_title: 同步上游
